name: chatbot4QC
dependencies:
  - python=3.11.4
  - psycopg2=2.9.3
  - pip=23.3
  - pip:
      - flake8==6.0.0
      - transformers==4.31.0
      - torch==2.0.1
      - scikit-learn==1.3.0
      - tabulate==0.9.0
      - tqdm==4.65.0
      - pandas==2.0.3
      - 'qiskit[visualization]'
      - tensorflow==2.13.0
      - transformers-interpret==0.10.0
      - simpletransformers==0.64.3
      - django==4.2.7
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.3.0
      - drf_yasg==1.21.7
      - pillow==10.1.0
      - django-cors-headers==4.3.0
      - psycopg2-binary==2.9.9
      - django-cleanup==8.0.0